### ISSUE TITLE
Y a pas de jeu

### ISSUE THREAD

**Issue by ADAMJordan97** [ValMgr/BonicheGaming#1]
bha y a pas de jeu
![Capture](https://user-images.githubusercontent.com/94146409/141378825-06f439e5-3439-4820-9224-dd414271df74.PNG)

**Comment by ValMgr** [comment]
Ah oe merde

**Comment by Tracnor** [comment]
r

**Comment by ADAMJordan97** [comment]
[https://www.youtube.com/watch?v=mZ_CDMyz374](url)

**Comment by ADAMJordan97** [comment]
https://www.youtube.com/watch?v=mZ_CDMyz374

**Comment by ValMgr** [comment]
Trop bien ton chat notamment
